
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Velocity Prime X',
    price: 12999.00,
    category: 'Sports',
    description: 'Engineered for speed and endurance, the Velocity Prime X features responsive cushioning and a breathable mesh upper.',
    images: ['https://i.ibb.co/svPccwn2/Lateral-Agility-Pivot.png', 'https://picsum.photos/seed/shoe1b/800/800'],
    colors: ['Orange', 'Black', 'White'],
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.8,
    reviewsCount: 124,
    isBestSeller: true,
  },
  {
    id: '2',
    name: 'Urban Glide Low',
    price: 6499.00,
    category: 'Men',
    description: 'The perfect daily driver. Minimalist aesthetics meets maximum comfort for the modern urban explorer.',
    images: ['https://picsum.photos/seed/shoe2/800/800', 'https://picsum.photos/seed/shoe2b/800/800'],
    colors: ['Grey', 'Navy'],
    sizes: [8, 9, 10, 11],
    rating: 4.5,
    reviewsCount: 86,
    isNewArrival: true,
  },
  {
    id: '3',
    name: 'Aura High Top',
    price: 9999.00,
    category: 'Women',
    description: 'Elevate your street style with Aura. Features premium leather and an iconic silhouette.',
    images: ['https://i.ibb.co/tpj8hGvZ/Ethereal-Light-Glow.png'],
    colors: ['White', 'Pastel Pink'],
    sizes: [5, 6, 7, 8, 9],
    rating: 4.9,
    reviewsCount: 210,
    isBestSeller: true,
  },
  {
    id: '4',
    name: 'Kids Zoomer',
    price: 2499.00,
    category: 'Kids',
    description: 'Durable, flexible, and fun. Designed to keep up with the most active little ones.',
    images: ['https://picsum.photos/seed/shoe4/800/800'],
    colors: ['Blue', 'Red', 'Yellow'],
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviewsCount: 45,
  },
  {
    id: '5',
    name: 'Summit Trail Blazer',
    price: 14999.00,
    category: 'Sports',
    description: 'Conquer any terrain. Waterproof, rugged, and ready for adventure.',
    images: ['https://picsum.photos/seed/shoe5/800/800'],
    colors: ['Olive', 'Earth', 'Black'],
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.6,
    reviewsCount: 72,
  },
  {
    id: '6',
    name: 'Nova Knit Runner',
    price: 8499.00,
    category: 'Women',
    description: 'Seamless knit upper provides a sock-like fit for effortless miles.',
    images: ['https://picsum.photos/seed/shoe6/800/800'],
    colors: ['Lilac', 'Cloud'],
    sizes: [6, 7, 8, 9],
    rating: 4.4,
    reviewsCount: 58,
    isNewArrival: true,
  },
  {
    id: '7',
    name: 'Elite Court Classic',
    price: 7499.00,
    category: 'Men',
    description: 'A timeless tennis-inspired silhouette that never goes out of style.',
    images: ['https://picsum.photos/seed/shoe7/800/800'],
    colors: ['White/Green', 'White/Blue'],
    sizes: [8, 9, 10, 11, 12],
    rating: 4.8,
    reviewsCount: 156,
  },
  {
    id: '8',
    name: 'Lunar Flux',
    price: 11999.00,
    category: 'Sports',
    description: 'Next-gen foam technology for gravity-defying bounce.',
    images: ['https://picsum.photos/seed/shoe8/800/800'],
    colors: ['Neon Green', 'Stealth'],
    sizes: [7, 8, 9, 10, 11],
    rating: 4.9,
    reviewsCount: 88,
  }
];

export const SIZES = [5, 6, 7, 8, 9, 10, 11, 12, 13];
export const COLORS = ['Black', 'White', 'Grey', 'Navy', 'Olive', 'Red', 'Blue', 'Pink'];
